### ISSUE TITLE
Chrome reports the extension as an unsupported extension

### ISSUE THREAD

**Issue by frsantos** [davidfou/conventionalcomments-web-extension#18]
**Describe the bug**
Chrome says in the extension page: 

> This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

**To Reproduce**

1. Go to https://chromewebstore.google.com/detail/conventional-comments/pagggmojbbphjnpcjeeniigdkglamffk

**Expected behavior**
Chrome does not report the extension as unsupported

**Screenshots**
![image](https://github.com/user-attachments/assets/f83e56d3-35a0-4d52-9ba4-4978d97e160a)

**Environment**
Information to reproduce the bug under the same conditions.

- OS [e.g. Linux, macOs]
- Browser [e.g. Chrome Version 124.0.6367.207, Firefox 129.0]
- Url [e.g. https://github.com, https://gitlab.acme.corp]

**Additional context**

- OS [e.g. Linux, macOs]
- Browser [e.g. Chrome Version 124.0.6367.207, Firefox 129.0]
- ...

**Comment by davidfou** [comment]
Most probably it's because the app is not on the manifest v3! I updated on the `new-build` branch but that's far from ready...

I hope it will not be much work to do it on the `main` branch. Thanks or raising my attention here!

**Comment by davidfou** [comment]
The new version is now accepted. I also hope it will help me to get back the "featured" badge. Thanks again for opening that issue.

If you use the extension and appreciate it, you'd do me a great favor to rate it on the store [page](https://chromewebstore.google.com/detail/conventional-comments/pagggmojbbphjnpcjeeniigdkglamffk)
