### ISSUE TITLE
Nitpick description is not inline with conventional-comments

### ISSUE THREAD

**Issue by guidovdijk** [davidfou/conventionalcomments-web-extension#27]
**Is your feature request related to a problem? Please describe.**
The description of the `nitpick` option is incorrect.
The extension states that nitpicks are "small, trivial, but necessary changes", while https://conventionalcomments.org/ states nitpicks are non-blocking.

**Describe the solution you'd like**
Change part of the description from "Nitpicks are small, trivial, but necessary changes" to something along the lines of: "Nitpicks are optional, small, and trivial changes"

**Comment by davidfou** [comment]
The version 2.3.3 contains the fix regarding the nitpick description. Thanks again for raising that issue!
