### ISSUE TITLE
Regression in latest Github

### ISSUE THREAD

**Issue by cpb** [davidfou/conventionalcomments-web-extension#3]
Hi!

My PR comment boxes no longer have the UI.

I'm using Firefox 119 and Chrome 119.0.6045.105

I tried cloning the repo and running the dev setup but I'm distracted from figuring out the canvas install issues.

**Comment by davidfou** [comment]
Hello @cpb :wave: 

Sorry for the very late reply. This was reported on the GitLab repo and fixed over there.

It should now work again!

Thanks for raising that issue and don't hesitate to reopen it if you still have issues.

**Comment by cpb** [comment]
> Hello @cpb :wave: 
> 
> Sorry for the very late reply. This was reported on the GitLab repo and fixed over there.
> 
> It should now work again!
> 
> Thanks for raising that issue and don't hesitate to reopen it if you still have issues.

No worries, I'll post there next time!
