### ISSUE TITLE
Adding dark theme for Github

### ISSUE THREAD

**Issue by nhkhang** [davidfou/conventionalcomments-web-extension#5]
It doesn't work well when I use Github dark theme. It would be really helpful if the extension can support dark theme on Github.

![Screen Shot 2024-03-20 at 12 35 19 AM](https://github.com/davidfou/conventionalcomments-web-extension/assets/45451597/272ce084-cb08-4e96-b013-5488a3a1d364)

**Comment by davidfou** [comment]
Thanks for raising that issue. An update on GitHub broke the extension, I'll have a look to fix it.
