### ISSUE TITLE
web extension is broken on Chrome + GitHub

### ISSUE THREAD

**Issue by rooterkyberian** [davidfou/conventionalcomments-web-extension#6]
Hi, I have seen [presentation](https://www.youtube.com/watch?v=Ndc_BSXHUuA) and was quite excited to use this extension.
Sadly, it seems that it doesn't work correctly at this time.

## Steps to reproduce
1) Install chrome extension
2) Try to add comment on a github PR (just click `+` at any line)

## Expected outcome:
Empty comment is opened and I can start typing either comment or `?ib` shortcut 

## Current outcome

Without me typing anything, the comment textbox is populated and some additional fields appear above it:
![image](https://github.com/davidfou/conventionalcomments-web-extension/assets/637466/c7571b7b-19fd-4120-9d4c-a4aeaf4a6b3b)

## Environment

Extension installed from: https://chromewebstore.google.com/detail/conventional-comments/pagggmojbbphjnpcjeeniigdkglamffk?hl=en
> 2.1.0

Google Chrome
> Version 125.0.6422.141 (Official Build) (64-bit)

User agent: 
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

**Comment by rooterkyberian** [comment]
I see this is a duplicate of #5 (despite the title, all themes are affected)

**Comment by davidfou** [comment]
Hello @rooterkyberian :wave: 

Thanks for opening the issue and indeed, it was already reported. At the moment I'm quite busy and I have trouble dedicating time to this extension. I still hope to correct this annoying issue soon.

In the video you shared, the speaker did a demo of the extension (the one broken) but the one with the shortcuts is another one. If you prefer the alternative proposed by the speaker, here is a link https://chromewebstore.google.com/detail/conventional-comments-ext/gfmhkklnfobogphbhknahninpcijjmad

**Comment by rooterkyberian** [comment]
thanks for correction!
